server:
  port: 8080

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]

      routes:
        # AUTH-SERVICE
        - id: auth-api
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/roles/**

        # CUSTOMER-SERVICE
        - id: customer-api
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**,/api/cities/**

        # ORDER-SERVICE
        - id: order-api
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**,/api/products/**,/api/order-statuses/**
        # PAYMENT-SERVICE
        - id: payment-api
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**,/api/payment-methods/**
        # PRODUCTIONSTAGES-SERVICE
        - id: productionStages-api      
          uri: lb://PRODUCTIONSTAGES-SERVICE
          predicates:
            - Path=/api/production-stages/**,/api/stage-types/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret: "MySuperSecretKeyForJwt1234567890MyExtra"
    access-expiration-ms: 900000
    refresh-expiration-ms: 604800000

management:
  endpoints:
    web:
      exposure:
        include: "*"
